<?php

abstract class TestCase extends Illuminate\Foundation\Testing\TestCase
{

    public function setUp()
    {
        exec('mkdir ' . __DIR__ .'/dump/');
        exec('touch ' . __DIR__ .'/dump/database.sql');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        exec('rm -rf ' . __DIR__ .'/dump/');
    }

    /**
     * The base URL to use while testing the application.
     *
     * @var string
     */
    protected $baseUrl = 'http://localhost';

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

        return $app;
    }
}
